name: ibm_presensi_app
description: "A new Flutter project for PT Intiboga Mandiri."
publish_to: "none"

version: 1.6.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  get_it: ^7.7.0
  shared_preferences: ^2.3.2
  equatable: ^2.0.5
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0

  retrofit: ^4.5.0 # 👈 Versi stabil
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # MAPS & GEOLOCATION
  flutter_osm_plugin: ^0.70.4
  geolocator: ^12.0.0
  geolocator_android: ^4.5.0
  permission_handler: ^11.3.1

  device_info_plus: ^11.1.0
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.2.2
  flutter_timezone: ^2.1.0

  flutter_face_api: ^6.4.1
  flutter_face_core_basic: ^6.4.0
  safe_device: ^1.1.6

  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  camera: ^0.10.5+9 # ✅ Versi stabil
  google_mlkit_face_detection: ^0.11.0
  elegant_notification: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_ibm.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_ibm.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_ibm.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/logo_ibm.png
    color: "#ffffff"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_ibm.png
    - assets/images/icon_ibm.png
